create table USER_DETAILS(
USER_ID VARCHAR(60) PRIMARY KEY,
FIRST_NAME VARCHAR(250),
LAST_NAME VARCHAR(250) ,
MOBILE_INT INT(10) Not Null,
EMAIL_ID VARCHAR(60) ,
PASSWORD VARCHAR(100) ,
ROLE_ID INT(2) Not Null,
ADDRESS_ID VARCHAR(50) Not Null,
STATUS VARCHAR(20) Not Null,
LAST_LOGIN DATE 
);

create table USER_ADDRESS_DETAILS(
ADDRESS_ID VARCHAR(50),
USER_ID VARCHAR(60),
ADDRESS_LINE_1 VARCHAR(500) Not Null,
ADDRESS_LINE_2 VARCHAR(500), 
CITY VARCHAR(200), 
DISTRICT VARCHAR(100) Not Null,
STATE VARCHAR(100) Not Null,
LAST_UPDATED date ,
PRIMARY KEY(ADDRESS_ID, USER_ID)
);

create table OTP_DETAILS(
MOBILE_INT INT(10) Not Null,
OTP VARCHAR(250) Not Null,
TIME_CREATED DATE Not Null
);

create table ROLE_DETAILS(
ROLE_ID INT(10) PRIMARY KEY,
ROLE_NAME VARCHAR(250) Not Null,
ROLE_DESCRIPTION VARCHAR(2000) ,
LAST_UPDATED DATE 
);


create table INBOX_LAYOUT
(
ROLE_ID INT(10) Not Null,
SECTION_ID INT(3) Not Null,
SECTION_HEADING VARCHAR(200) Not Null,
SECTION_TEXT VARCHAR(500) ,
SECTION_ITEM_ID INT(10) Not Null,
SECTION_ITEM_NAME VARCHAR(250) Not Null,
SECTION_ITEM_ICON_NAME VARCHAR(250) Not Null,
SECTION_ITEM_URL VARCHAR(250) Not Null,
SECTION_ITEM_DESCRIPTION VARCHAR(2000) ,
SECTION_SEQUENCE INT(3) ,
LAST_UPDATED DATE ,
PRIMARY KEY(ROLE_ID, SECTION_ID, SECTION_ITEM_ID)
);


create table INBOX_USER_CUSTOMIZATION
(
USER_ID VARCHAR(60) Not Null,
SECTION_ID INT(3) Not Null,
SECTION_ITEM_ID INT(10) Not Null,
SECTION_ITEM_NAME VARCHAR(250) Not Null,
SECTION_ITEM_ICON_NAME VARCHAR(250) Not Null,
SECTION_ITEM_DESCRIPTION VARCHAR(2000) ,
SECTION_ITEM_URL VARCHAR(250) Not Null,
PRIMARY KEY(USER_ID, SECTION_ID, SECTION_ITEM_ID)
);

create table SUB_MENU_ITEMS
(
SECTION_ITEM_ID INT(10) Not Null,
SUBSEC_ITEM_NAME VARCHAR(250) Not Null,
SUBSEC_ITEM_ICON_NAME VARCHAR(250) Not Null,
SUBSEC_ITEM_DESCRIPTION VARCHAR(2000) ,
SUBSEC_ITEM_URL VARCHAR(250) Not Null,
SUBSEC_ITEM_SEQ INT(3) ,
PRIMARY KEY(SECTION_ITEM_ID, SUBSEC_ITEM_NAME)
);

create table PROCESS_DEFINITIONS
(
Process_ID INT(10) Not Null,
Process_Name VARCHAR(200) Not Null,
Stage_Name VARCHAR(200) Not Null,
Stage_seq INT(3) Not Null,
Parent_Stage INT(3) Not Null,
Stage_optional VARCHAR(1) ,
APPROVER_ROLE_ID_1 INT(10) Not Null,
APPROVER_ROLE_ID_2 INT(10) ,
APPROVER_ROLE_ID_3 INT(10) ,
APPROVER_ROLE_ID_4 INT(10) ,
APPROVER_ROLE_ID_5 INT(10) 
);

create table USER_MOD_REQUESTS
(
USER_ID VARCHAR(60) Not Null,
Process_ID INT(10) Not Null,
Stage_seq INT(3) Not Null,
Expiry_date DATE Not Null,
STATUS VARCHAR(10) Not Null,
Stage_start_date DATE Not Null,
Stage_completed DATE ,
Stage_outcome VARCHAR(50), 
Remarks VARCHAR(2000) 
);
